package analysejob.common.job.counter;

public enum FSCounterKey {
	FILE_BYTES_READ,
	FILE_BYTES_WRITTEN,
	FILE_READ_OPS,
	FILE_LARGE_READ_OPS,
	FILE_WRITE_OPS,
	HDFS_BYTES_READ,
	HDFS_BYTES_WRITTEN,
	HDFS_READ_OPS,
	HDFS_LARGE_READ_OPS,
	HDFS_WRITE_OPS  
}