package analysejob.common.job.counter;

public enum JobCounterKey {
	TOTAL_LAUNCHED_MAPS,
	TOTAL_LAUNCHED_REDUCES,
	RACK_LOCAL_MAPS,
	SLOTS_MILLIS_MAPS,
	SLOTS_MILLIS_REDUCES,
	FALLOW_SLOTS_MILLIS_MAPS,
	FALLOW_SLOTS_MILLIS_REDUCES  
}
