package analysejob.common.job.counter;

public enum TaskCounterKey {
	MAP_INPUT_RECORDS,
	MAP_OUTPUT_RECORDS,
	MAP_OUTPUT_BYTES,
	SPLIT_RAW_BYTES,
	COMBINE_INPUT_RECORDS,
	COMBINE_OUTPUT_RECORDS,
	REDUCE_INPUT_GROUPS,
	REDUCE_SHUFFLE_BYTES,
	REDUCE_INPUT_RECORDS,
	REDUCE_OUTPUT_RECORDS,
	SPILLED_RECORDS,
	CPU_MILLISECONDS,
	PHYSICAL_MEMORY_BYTES,
	VIRTUAL_MEMORY_BYTES,
	COMMITTED_HEAP_BYTES  
}
